[tool.cibuildwheel]
environment = { PIP_NO_BUILD_ISOLATION = "false" }
build-verbosity = 3

manylinux-aarch64-image = "manylinux_2_28"
manylinux-x86_64-image = "manylinux_2_28"

[tool.cibuildwheel.linux]
build = "cp38-* cp39-* cp310-* cp311-* cp312-*"
skip = ["*-manylinux_i686", "*-musllinux*"]
environment-pass = [
    "PIP_NO_BUILD_ISOLATION",
]
before-build = [
    "rm -rf {project}/build",
    "rm -rf *egg*",
    "pip install -r requirements-dev.txt",
    "yum install -y epel-release && yum install -y ninja-build cmake openssl openssl-devel boost-devel protobuf-devel libdrm-devel ocl-icd-devel systemtap-sdt-devel rapidjson ncurses-devel zlib-static libuuid-devel"
]

[tool.cibuildwheel.macos]
build = "cp38-* cp39-* cp310-* cp311-* cp312-*"
before-build = [
    "rm -rf {project}/build",
    "rm -rf *egg*",
    "pip install -r requirements-dev.txt",
]

[tool.cibuildwheel.windows]
build = "cp38-win_amd64 cp39-win_amd64 cp310-win_amd64 cp311-win_amd64 cp312-win_amd64"
before-build = [
    "rm -rf {project}/build",
    "rm -rf *egg*",
    "pip install -r requirements-dev.txt",
]
