[tool.cibuildwheel]
environment = { PIP_NO_BUILD_ISOLATION = "false" }
build-verbosity = 3
build = "cp38-* cp39-* cp310-* cp311-* cp312-*"
manylinux-aarch64-image = "manylinux_2_28"
manylinux-x86_64-image = "manylinux_2_28"

[tool.cibuildwheel.linux]
skip = ["*-manylinux_i686", "*-musllinux*"]
environment-pass = [
    "PIP_NO_BUILD_ISOLATION",
]
before-build = [
    "rm -rf {project}/build",
    "rm -rf *egg*",
    "pip install -r requirements-dev.txt",
    "yum install -y epel-release && yum install -y ninja-build cmake openssl openssl-devel boost-devel protobuf-devel libdrm-devel ocl-icd-devel systemtap-sdt-devel rapidjson ncurses-devel zlib-static libuuid-devel"
]
repair-wheel-command = [
    "auditwheel repair -w {dest_dir} {wheel} --exclude libxrt_coreutil.so"
]

[tool.cibuildwheel.macos]
before-build = [
    "rm -rf {project}/build",
    "rm -rf *egg*",
    "pip install -r requirements-dev.txt",
]

[tool.cibuildwheel.windows]
skip = ["*-win32"]
before-build = [
    "rm -rf {project}/build",
    "rm -rf *egg*",
    "pip install delvewheel",
    "pip install -r requirements-dev.txt",
]
repair-wheel-command = [
    "delvewheel repair -v -w {dest_dir} {wheel} --no-dll xrt_coreutil.dll"
]
