name: Wheels

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  build:

    continue-on-error: true

    runs-on: ${{ matrix.OS }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - OS: ubuntu-20.04
            ARCH: x86_64

          - OS: windows-2019
            ARCH: AMD64

          - OS: macos-12
            ARCH: x86_64

          - OS: macos-12
            ARCH: arm64

    defaults:
      run:
        shell: bash

    steps:

      - name: Checkout actions
        uses: actions/checkout@v3
        with:
          submodules: true

      - uses: ./.github/workflows/base
        if: contains(matrix.OS, 'windows')
        id: base
        with:
          OS: ${{ matrix.OS }}
          ARCH: ${{ matrix.ARCH }}

      - name: Build and install protoc
        if: contains(matrix.OS, 'windows')
        run: |
          
          choco install -y pkgconfiglite protoc 

      # build

      - name: cibuildwheel python bindings
        env:
          BOOST_ROOT: ${{ steps.base.outputs.BOOST_ROOT }}
          BOOST_VERSION: 1.73.0
        run: |

          pip install cibuildwheel
          cibuildwheel --output-dir wheelhouse

      # done

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          path: wheelhouse/*.whl
          name: build_artifact_python_bindings

  build-linux-aarch64:

    continue-on-error: true

    runs-on: ubuntu-20.04

    steps:

      - name: Checkout actions
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: aarch64

      # build

      - name: cibuildwheel python bindings aarch64
        env:
          BOOST_ROOT: ${{ steps.base.outputs.BOOST_ROOT }}
          BOOST_VERSION: 1.73.0
        run: |
          
          pip install cibuildwheel
          cibuildwheel --output-dir wheelhouse

      # done

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          path: wheelhouse/*.whl
          name: build_artifact_python_bindings

  upload_bindings_wheels:

    if: github.event_name != 'pull_request' && github.ref_name == 'main'

    needs: [build, build-linux-aarch64]

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/download-artifact@v3
        with:
          # unpacks default artifact into dist/
          # if `name: artifact` is omitted, the action will create extra parent dir
          name: build_artifact_python_bindings
          path: dist

      - name: Release current commit
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "dist/*.whl"
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "latest"
          name: "latest"
          removeArtifacts: false
          allowUpdates: true
          replacesArtifacts: true
          makeLatest: true
