name: Wheels

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [assigned, opened, synchronize, reopened]

concurrency:
  group: test-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:

  build:

    continue-on-error: true

    runs-on: ${{ matrix.OS }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - OS: ubuntu-20.04
            ARCH: x86_64

          - OS: windows-2019
            ARCH: AMD64

    defaults:
      run:
        shell: bash

    steps:

      - name: Checkout actions
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Get Submodules
        run: |
          
          git submodule update --init --recursive

      - uses: ./.github/workflows/base
        id: base
        with:
          OS: ${{ matrix.OS }}
          ARCH: ${{ matrix.ARCH }}
          PY_VERSION: '3.10'

      # build

      - name: cibuildwheel python bindings
        env:
          BOOST_ROOT: ${{ steps.base.outputs.BOOST_ROOT }}
          BOOST_VERSION: ${{ steps.base.outputs.BOOST_VERSION }}
        run: |

          REPO_SRC_DIR=$PWD bash patches/apply_patches.sh
          CIBW_BUILD="cp38-* cp39-* cp310-* cp311-* cp312-*" \
            cibuildwheel --output-dir wheelhouse

      # done

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          path: wheelhouse/*.whl
          name: build_artifact_python_bindings

  build-linux-aarch64:

    continue-on-error: true

    runs-on: ubuntu-20.04

    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: aarch64

      - name: Checkout actions
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Get Submodules
        run: |
          
          git submodule update --init --recursive

      - uses: ./.github/workflows/base
        id: base
        with:
          OS: ubuntu-20.04
          ARCH: aarch64
          PY_VERSION: '3.10'

      # build

      - name: cibuildwheel python bindings aarch64
        env:
          BOOST_ROOT: ${{ steps.base.outputs.BOOST_ROOT }}
          BOOST_VERSION: ${{ steps.base.outputs.BOOST_VERSION }}
        run: |
          
          REPO_SRC_DIR=$PWD bash patches/apply_patches.sh
          CIBW_BUILD="cp38-* cp39-* cp310-* cp311-* cp312-*" \
            cibuildwheel --output-dir wheelhouse

      # done

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          path: wheelhouse/*.whl
          name: build_artifact_python_bindings

  upload_bindings_wheels:

    if: github.event_name != 'pull_request'

    needs: [build, build-linux-aarch64]

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/download-artifact@v3
        with:
          # unpacks default artifact into dist/
          # if `name: artifact` is omitted, the action will create extra parent dir
          name: build_artifact_python_bindings
          path: dist

      - name: Release current commit
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "dist/*.whl"
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag: ${{ github.ref_name == 'main' && 'release' || 'dev' }}
          name: ${{ github.ref_name == 'main' && 'release' || 'dev' }}
          removeArtifacts: false
          allowUpdates: true
          replacesArtifacts: true
          makeLatest: true
          omitBody: true
